<?php

namespace Database\Seeders;

use App\Models\CoffeeShop;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CoffeeShopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $realCoffeeShops = [
            [
                'name' => 'Titik Temu Coffee - Senopati',
                'slug' => Str::slug('Titik Temu Coffee Senopati'),
                'description' => 'Coffee shop ikonik di Senopati dengan perpaduan desain modern dan area taman hijau yang asri. Pilihan tepat untuk santai sore maupun meeting santai.',
                'address' => 'Jl. Senopati No. 27, Kebayoran Baru',
                'city' => 'Jakarta Selatan',
                'latitude' => -6.234381,
                'longitude' => 106.809142,
                'phone' => '081288991234',
                'instagram' => '@titiktemucoffee',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
                'price_min' => 35000,
                'price_max' => 75000,
                'price_range' => '$$',
                'rating' => 4.65,
                'review_count' => 420,
                'opening_time' => '07:00:00',
                'closing_time' => '22:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'aesthetic',
                'wifi_speed_mbps' => 75,
                'noise_level' => 'moderate',
                'is_active' => true,
            ],
            [
                'name' => 'Kopi Toko Djawa - Braga',
                'slug' => Str::slug('Kopi Toko Djawa Braga'),
                'description' => 'Kedai kopi legendaris di jalan bersejarah Braga, menyajikan Es Kopi Awan dengan nuansa vintage nostalgia dan aroma toko buku lawas.',
                'address' => 'Jl. Braga No. 81, Sumur Bandung',
                'city' => 'Bandung',
                'latitude' => -6.917464,
                'longitude' => 107.609810,
                'phone' => '082123456789',
                'instagram' => '@kopitokodjawa',
                'image_url' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
                'price_min' => 20000,
                'price_max' => 40000,
                'price_range' => '$',
                'rating' => 4.70,
                'review_count' => 1250,
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
                'has_wifi' => true,
                'has_power_outlets' => false,
                'is_ac' => true,
                'is_outdoor' => false,
                'is_smoking_area' => false,
                'is_work_friendly' => false,
                'has_prayer_room' => false,
                'ambiance' => 'cozy',
                'wifi_speed_mbps' => 30,
                'noise_level' => 'loud',
                'is_active' => true,
            ],
            [
                'name' => 'Kroma Coffee - Dharmawangsa',
                'slug' => Str::slug('Kroma Coffee Dharmawangsa'),
                'description' => 'Sanctuary tenang bernuansa minimalis ala Jepang di Dharmawangsa. Didesain khusus untuk para pencari fokus WFC (Work from Cafe) dengan colokan melimpah.',
                'address' => 'Jl. Panglima Polim V No. 25B, Melawai, Kebayoran Baru',
                'city' => 'Jakarta Selatan',
                'latitude' => -6.251400,
                'longitude' => 106.797200,
                'phone' => '081399887766',
                'instagram' => '@kroma.id',
                'image_url' => 'https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=800&q=80',
                'price_min' => 28000,
                'price_max' => 60000,
                'price_range' => '$$',
                'rating' => 4.82,
                'review_count' => 510,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'minimalist',
                'wifi_speed_mbps' => 100,
                'noise_level' => 'quiet',
                'is_active' => true,
            ],
            [
                'name' => 'Raindear Coffee & Kitchen - Bogor',
                'slug' => Str::slug('Raindear Coffee Kitchen Bogor'),
                'description' => 'Kafe luas dan modern di jantung Kota Hujan Bogor. Terkenal dengan Es Kopi Bogor dan area indoor maupun outdoor yang lapang dan sejuk.',
                'address' => 'Jl. Bina Marga I No. 7, Baranangsiang',
                'city' => 'Bogor',
                'latitude' => -6.602500,
                'longitude' => 106.812300,
                'phone' => '02518334455',
                'instagram' => '@raindearcoffee',
                'image_url' => 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80',
                'price_min' => 30000,
                'price_max' => 85000,
                'price_range' => '$$',
                'rating' => 4.75,
                'review_count' => 920,
                'opening_time' => '07:00:00',
                'closing_time' => '23:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'aesthetic',
                'wifi_speed_mbps' => 60,
                'noise_level' => 'moderate',
                'is_active' => true,
            ],
            [
                'name' => 'Space Coffee Roastery - Yogyakarta',
                'slug' => Str::slug('Space Coffee Roastery Yogyakarta'),
                'description' => 'Roastery dan coffee shop spesialisasi filter coffee dan single origin terbaik di Yogyakarta dengan ambience industrial yang tenang.',
                'address' => 'Gg. Pandean No. 23, Sorosutan, Umbulharjo',
                'city' => 'Yogyakarta',
                'latitude' => -7.824100,
                'longitude' => 110.389200,
                'phone' => '081290001122',
                'instagram' => '@space.roastery',
                'image_url' => 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
                'price_min' => 22000,
                'price_max' => 50000,
                'price_range' => '$',
                'rating' => 4.88,
                'review_count' => 740,
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'industrial',
                'wifi_speed_mbps' => 120,
                'noise_level' => 'quiet',
                'is_active' => true,
            ],
            [
                'name' => 'Popolo Coffee - Sentul',
                'slug' => Str::slug('Popolo Coffee Sentul'),
                'description' => 'Kafe berkonsep glasshouse transparan yang dikelilingi pepohonan hijau asri Sentul. Suasana adem dan menenangkan pikiran.',
                'address' => 'Summarecon Sentul, Babakan Madang',
                'city' => 'Bogor',
                'latitude' => -6.559200,
                'longitude' => 106.885600,
                'phone' => '02187951234',
                'instagram' => '@popolocoffee',
                'image_url' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
                'price_min' => 25000,
                'price_max' => 65000,
                'price_range' => '$$',
                'rating' => 4.70,
                'review_count' => 610,
                'opening_time' => '09:00:00',
                'closing_time' => '20:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'nature',
                'wifi_speed_mbps' => 50,
                'noise_level' => 'moderate',
                'is_active' => true,
            ],
            [
                'name' => 'Tanamera Coffee - Thamrin City',
                'slug' => Str::slug('Tanamera Coffee Thamrin City'),
                'description' => 'Pionir specialty coffee Indonesia dengan roast beans berkualitas juara internasional. Cocok untuk business meeting profesional.',
                'address' => 'Thamrin City Office Park, Jl. Kebon Kacang Raya',
                'city' => 'Jakarta Pusat',
                'latitude' => -6.195600,
                'longitude' => 106.818900,
                'phone' => '02123579999',
                'instagram' => '@tanameracoffee',
                'image_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
                'price_min' => 40000,
                'price_max' => 95000,
                'price_range' => '$$$',
                'rating' => 4.62,
                'review_count' => 830,
                'opening_time' => '07:00:00',
                'closing_time' => '21:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => false,
                'is_smoking_area' => false,
                'is_work_friendly' => true,
                'has_prayer_room' => false,
                'ambiance' => 'industrial',
                'wifi_speed_mbps' => 150,
                'noise_level' => 'quiet',
                'is_active' => true,
            ],
            [
                'name' => 'Armor Kopi - Dago Pakar',
                'slug' => Str::slug('Armor Kopi Dago Pakar'),
                'description' => 'Menikmati seduhan kopi arabika lokal di tengah hutan pinus Dago yang sejuk dan berkabut, ditemani aneka camilan tradisional.',
                'address' => 'Jl. Bukit Pakar Utara No. 10, Ciburial',
                'city' => 'Bandung',
                'latitude' => -6.861200,
                'longitude' => 107.632100,
                'phone' => '081222334455',
                'instagram' => '@armorkopi.bdg',
                'image_url' => 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
                'price_min' => 18000,
                'price_max' => 45000,
                'price_range' => '$',
                'rating' => 4.58,
                'review_count' => 1500,
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
                'has_wifi' => false,
                'has_power_outlets' => false,
                'is_ac' => false,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => false,
                'has_prayer_room' => true,
                'ambiance' => 'nature',
                'wifi_speed_mbps' => null,
                'noise_level' => 'moderate',
                'is_active' => true,
            ],
            [
                'name' => 'Kopi Nako - Pajajaran Bogor',
                'slug' => Str::slug('Kopi Nako Pajajaran Bogor'),
                'description' => 'Kedai kopi berkonsep arsitektur kaca nako geometris kontemporer, menyediakan area nongkrong outdoor berundak yang luas dan asyik.',
                'address' => 'Jl. Pajajaran Indah V No. 7, Baranangsiang',
                'city' => 'Bogor',
                'latitude' => -6.608700,
                'longitude' => 106.814500,
                'phone' => '02518339876',
                'instagram' => '@kopinako.id',
                'image_url' => 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80',
                'price_min' => 20000,
                'price_max' => 48000,
                'price_range' => '$',
                'rating' => 4.68,
                'review_count' => 1340,
                'opening_time' => '08:00:00',
                'closing_time' => '23:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => true,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => true,
                'has_prayer_room' => true,
                'ambiance' => 'industrial',
                'wifi_speed_mbps' => 40,
                'noise_level' => 'moderate',
                'is_active' => true,
            ],
            [
                'name' => 'Kala Cemara - Lembang',
                'slug' => Str::slug('Kala Cemara Lembang'),
                'description' => 'Tempat ngopi pinggir danau dengan pemandangan pegunungan Lembang Bandung yang romantis dan sejuk, cantik saat senja tiba.',
                'address' => 'Jl. Sersan Bajuri No. 102, Cihideung, Parongpong',
                'city' => 'Bandung',
                'latitude' => -6.832400,
                'longitude' => 107.595400,
                'phone' => '081299881122',
                'instagram' => '@kalacemara',
                'image_url' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
                'price_min' => 25000,
                'price_max' => 70000,
                'price_range' => '$$',
                'rating' => 4.72,
                'review_count' => 490,
                'opening_time' => '10:00:00',
                'closing_time' => '21:00:00',
                'has_wifi' => true,
                'has_power_outlets' => true,
                'is_ac' => false,
                'is_outdoor' => true,
                'is_smoking_area' => true,
                'is_work_friendly' => false,
                'has_prayer_room' => true,
                'ambiance' => 'nature',
                'wifi_speed_mbps' => 30,
                'noise_level' => 'quiet',
                'is_active' => true,
            ],
        ];

        foreach ($realCoffeeShops as $shop) {
            CoffeeShop::updateOrCreate(
                ['slug' => $shop['slug']],
                $shop
            );
        }

        // Tambahkan 15 data faker bervariasi untuk pengujian filter & scoring lengkap
        CoffeeShop::factory()->count(15)->create();
    }
}
